#pragma once
// ╔══════════════════════════════════════════════════════════════════════╗
// ║  DeMoD DSP GUI — Faust DSP Bridge                                  ║
// ║                                                                    ║
// ║  Loads Faust DSP code (either JIT via libfaust or pre-compiled     ║
// ║  C++ via dlopen) and provides a unified interface for:             ║
// ║    • Parameter discovery and control                               ║
// ║    • Audio processing callback                                     ║
// ║    • UI metadata extraction                                        ║
// ║                                                                    ║
// ║  Supports two loading modes:                                       ║
// ║    1. JIT: Pass .dsp source → libfaust compiles at runtime         ║
// ║    2. DSO: Pass .so/.dylib → dlopen pre-compiled Faust module     ║
// ╚══════════════════════════════════════════════════════════════════════╝

#include "core/config.hpp"
#include <string>
#include <vector>
#include <functional>
#include <memory>
#include <mutex>
#include <unordered_map>

namespace demod::audio {

// ── Faust UI visitor ─────────────────────────────────────────────────
// Minimal Meta/UI interface matching Faust's architecture headers.
// We implement this to discover parameters without pulling in the
// full Faust architecture headers.

class FaustParamUI {
public:
    void declare(float* /*zone*/, const char* key, const char* value);

    void openTabBox(const char* label);
    void openHorizontalBox(const char* label);
    void openVerticalBox(const char* label);
    void closeBox();

    void addButton(const char* label, float* zone);
    void addCheckButton(const char* label, float* zone);
    void addVerticalSlider(const char* label, float* zone,
                            float init, float min, float max, float step);
    void addHorizontalSlider(const char* label, float* zone,
                              float init, float min, float max, float step);
    void addNumEntry(const char* label, float* zone,
                      float init, float min, float max, float step);

    // Bargraphs (output-only meters)
    void addHorizontalBargraph(const char* label, float* zone,
                                float min, float max);
    void addVerticalBargraph(const char* label, float* zone,
                              float min, float max);

    const std::vector<ParamDescriptor>& params() const { return params_; }
    const std::vector<float*>& zones() const { return zones_; }
    const std::vector<std::pair<std::string, float*>>& meters() const {
        return meters_;
    }

private:
    std::vector<ParamDescriptor> params_;
    std::vector<float*> zones_;             // Zone pointers parallel to params_
    std::vector<std::pair<std::string, float*>> meters_;
    std::string current_path_;
    int param_index_ = 0;

    std::string make_path(const char* label) const;
};

// ── Abstract DSP interface ───────────────────────────────────────────
// Matches Faust's `dsp` base class signature.
class FaustDSP {
public:
    virtual ~FaustDSP() = default;
    virtual int getNumInputs()  = 0;
    virtual int getNumOutputs() = 0;
    virtual void buildUserInterface(FaustParamUI* ui) = 0;
    virtual int getSampleRate() = 0;
    virtual void init(int sample_rate) = 0;
    virtual void instanceInit(int sample_rate) = 0;
    virtual void instanceConstants(int sample_rate) = 0;
    virtual void instanceResetUserInterface() = 0;
    virtual void instanceClear() = 0;
    virtual void compute(int count, float** inputs, float** outputs) = 0;
    virtual FaustDSP* clone() = 0;
    virtual void metadata(/* Meta* */) {}
};

// ── Faust Bridge ─────────────────────────────────────────────────────
class FaustBridge {
public:
    FaustBridge();
    ~FaustBridge();

    // Load from .dsp source (requires libfaust JIT)
    bool load_dsp_source(const std::string& filepath, int sample_rate);

    // Load from pre-compiled shared object
    bool load_dsp_library(const std::string& so_path, int sample_rate);

    // Load from a C++ source generated by faust -lang cpp
    // (compiled and dlopened at runtime)
    bool load_dsp_cpp(const std::string& cpp_path, int sample_rate);

    // Unload current DSP
    void unload();
    bool loaded() const { return dsp_ != nullptr || jit_dsp_ != nullptr; }

    // ── Parameter access ─────────────────────────────────────────────
    const std::vector<ParamDescriptor>& params() const { return ui_.params(); }
    int num_params() const { return (int)ui_.params().size(); }

    // Get/set by index
    float get_param(int index) const;
    void  set_param(int index, float value);

    // Get/set by path (e.g., "/synth/cutoff")
    float get_param(const std::string& path) const;
    void  set_param(const std::string& path, float value);

    // Reset all params to defaults
    void reset_params();

    // Randomize all params within their ranges
    void randomize_params();

    // ── Audio processing ─────────────────────────────────────────────
    // Called from audio thread. Thread-safe parameter reads.
    void process(const float* const* inputs, float* const* outputs,
                 int n_channels, int n_frames);

    // Convenience: generate interleaved stereo output (no input)
    void process_interleaved(float* interleaved_out, int n_frames);

    // Duplex: non-interleaved input → DSP → interleaved output
    void process_interleaved(const float* const* inputs,
                             float* interleaved_out, int n_frames);

    // ── Metadata ─────────────────────────────────────────────────────
    std::string dsp_name()   const { return dsp_name_; }
    int         num_inputs() const { return num_inputs_; }
    int         num_outputs()const { return num_outputs_; }

    // ── Axis mapping ─────────────────────────────────────────────────
    // Map a continuous axis value (0.0–1.0) to a parameter
    struct AxisMapping {
        int   param_index;
        float axis_min;    // Axis value at param min
        float axis_max;    // Axis value at param max
        bool  bidirectional; // If true, 0.5 = center = default
    };

    void add_axis_mapping(Action axis_action, AxisMapping mapping);
    void clear_axis_mappings();

    // Apply axis values from input manager
    void apply_axis(Action axis_action, float value);

private:
    FaustDSP*     dsp_ = nullptr;
    FaustParamUI  ui_;
    void*         dl_handle_ = nullptr;

    // JIT-specific (libfaust)
    void*         jit_factory_ = nullptr;  // llvm_dsp_factory* (opaque)
    void*         jit_dsp_     = nullptr;  // faust dsp* (opaque)

    std::string dsp_name_;
    int num_inputs_  = 0;
    int num_outputs_ = 0;

    // Parameter zone pointers (direct memory access for RT thread)
    std::vector<float*> param_zones_;

    // Axis mappings
    std::unordered_map<Action, std::vector<AxisMapping>> axis_mappings_;

    // Deinterleave buffers
    std::vector<std::vector<float>> deinterleave_buf_;

    mutable std::mutex param_mutex_; // For non-RT parameter operations
};

} // namespace demod::audio
